version: '3.6'

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    env_file:
      - .env
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
      - /usr/src/smart-brain-api/node_modules/

  # Postgres
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
